project:
  type: website
  output-dir: docs
  resources:
    - contributing/ccla.pdf
    - contributing/icla.pdf
    - LICENSE

highlight-style: ayu
code-annotations: hover

execute:
  warning: false
  error: false
  cache: true

website:
  title: "Tergite"
  site-url: https://tergite.github.io
  description: "the software stack for the Swedish quantum computer"
  favicon: assets/img/shared/logo.svg

  # nav
  navbar:
    logo: assets/img/shared/logo.svg
    tools:
      - icon: github
        menu:
          - text: Source code
            url: https://github.com/tergite/tergite.github.io

    left:
      - sidebar:guides-list
      - sidebar:examples-list

    right:
      - sidebar:release-notes
      - sidebar:contribute

  # options
  reader-mode: false
  back-to-top-navigation: true
  repo-url: https://github.com/tergite/tergite.github.io

  # footer
  page-footer:
    border: false
    left: ""
    right:
      - icon: github
        href: https://github.com/tergite/tergite.github.io

  sidebar:
    - id: ""
    - id: guides-list
      title: "Guides"
      style: "docked"
      collapse-level: 2
      contents:
        - auto: tutorials
    - id: examples-list
      title: "Examples"
      style: "docked"
      collapse-level: 2
      contents:
        - auto: examples
    - id: contribute
      title: "Contribute"
      style: "docked"
      collapse-level: 2
      contents:
        - auto: contributing
    - id: release-notes
      title: "Release notes"
      style: "docked"
      collapse-level: 2
      contents:
        - auto: release_notes

format:
  html:
    theme:
      light: [simplex, assets/styles/shared-theme.scss]
      dark:
        [
          simplex,
          assets/styles/shared-theme.scss,
          assets/styles/dark-theme.scss,
        ]
    css: styles.css
    toc: true
    highlight-style: nord
    code-copy: true
    link-external-icon: true
    link-external-newwindow: true
