project:
  type: website
  output-dir: docs
  resources:
    - contributing/ccla.pdf
    - contributing/icla.pdf

highlight-style: ayu
code-annotations: hover

execute:
  warning: false
  error: false
  cache: true

website:
  title: "Tergite"
  site-url: https://tergite.github.io
  description: "the software stack for the Swedish quantum computer"
  favicon: assets/logo-light.svg

  # nav
  navbar:
    logo: assets/logo.svg
    tools:
      - icon: github
        menu:
          - text: Source code
            url: https://github.com/tergite

    left:
      - sidebar:guides-list

    right:
      - release_notes.qmd
      - sidebar:contribute

  # options
  reader-mode: false
  back-to-top-navigation: true
  repo-url: https://github.com/tergite

  # footer
  page-footer:
    border: false
    left: ""
    right:
      - icon: github
        href: https://github.com/tergite

  sidebar:
    - id: ""
    - id: guides-list
      title: "Guides"
      style: "docked"
      collapse-level: 2
      contents:
        - quick_start.qmd
        - auto: tutorials/*.qmd
    - id: contribute
      title: "Contribute"
      style: "docked"
      collapse-level: 2
      contents:
        - auto: contributing

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    highlight-style: github
    code-copy: true
